import 'package:queestudiar/question.dart';

class QuizBrain{

  List<Question> questionBank = [
    Question('Estoy orgulloso(a) de tener un amplio vocabulario', 1,1),
    Question('Me resulta fácil manejar diversos símbolos numéricos', 2,2),
    Question('La música es un componente altamente significativo de mi existencia',3,6),
    Question('Siempre sé exactamente donde estoy ubicado en relación a mi casa', 4,3),
    Question('Me considero un atleta', 5,4),
    Question('Siento que le agrado y caigo bien a las personas de todas las edades', 1,7),
    Question('A menudo busco en mí las debilidades que yo observo en los demás', 1,8),
    Question('Disfruto y obtengo alegrías del mundo viviente que me rodea', 1,5),
    Question('Me gusta aprender cada día nuevas palabras y lo hago con facilidad', 1,1),
    Question('Frecuentemente desarrollo ecuaciones que describen relaciones y explican mis observaciones', 2,2),
    Question('Tengo intereses musicales amplios que incluyen tanto lo contemporáneo como lo clásico',3,6),
    Question('No me pierdo con facilidad y sé orientarme con mapas o planos sobre puntos y direcciones que me son desconocidas', 4,3),
    Question('Me siento orgulloso de mantenerme físicamente bien, me agrada sentirme fuerte y sano', 5,4),
    Question('Respondo a los demás con entusiasmo sin prejuicios o medias palabras', 1,7),
    Question('Con frecuencia pienso acerca de la influencia que tengo sobre los demás', 1,8),
    Question('Me fascinan los cambios en las estaciones', 1,5),
    Question('Me agrada escuchar conferencias que me planteen retos', 1,1),
    Question('Con frecuencia establezco razones y relaciones en el mundo físico que me circundan', 2,2),
    Question('Tengo un sentido muy agudo de los tonos, el tiempo y el ritmo en la música',3,6),
    Question('Me resulta fácil conocer las direcciones en los lugares nuevos para mí', 4,3),
    Question('Tengo un excelente equilibrio y buena coordinación ojo/mano y me resulta atrayente los deportes  como el voley, tenis, fútbol, etc.', 5,4),
    Question('Me encanta compartir con una variedad de personas', 1,7),
    Question('Creo firmemente que soy responsable de quién soy yo y que mi "ser" es producto de mis elecciones personales', 1,8),
    Question('Me encanta la jardinería y cuidar las plantas de mi casa', 1,5),
    Question('Me gusta escribir un diario, con todas mis experiencias personales', 1,1),
    Question('Las matemáticas siempre han sido uno de mis cursos favoritos y voluntariamente he seguido mejorando en el curso de matemáticas', 2,2),
    Question('Mi educación musical empezó cuando yo era niño(a) y continúa hasta el momento',3,6),
    Question('Tengo la habilidad de representar lo que yo soy a través del dibujo o la pintura', 4,3),
    Question('Mi excelente equilibrio y coordinación de movimientos me permiten disfrutar de actividades de mucha velocidad', 5,4),
    Question('Me siento cómodo disfrutando de situaciones sociales nuevas', 1,7),
    Question('Frecuentemente pienso que la vida hay que aprovecharla al máximo por lo que no malgasto mi tiempo en cosas sin importancia', 1,8),
    Question('Observo con agrado, la fauna silvestre y me gusta dar de comer a las aves', 1,5),
    Question('Leo y disfruto de la poesía y ocasionalmente escribo poemas', 1,1),
    Question('Me agrada y discuto con otros sobre temas y datos de estadística y cálculos numéricos', 2,2),
    Question('Soy una persona con habilidades tanto en música instrumental como vocal',3,6),
    Question('Mi habilidad para dibujar es reconocida por los demás', 4,3),
    Question('Disfruto mucho de actividades al aire libre', 5,4),
    Question('Les caigo bien a los niños desde el primer instante que los conozco', 1,7),
    Question('Me agrada mucho leer sobre los grandes filósofos que han escrito sobre sus afanes, sus luchas, las alegrías y el amor de la vida', 1,8),
    Question('En alguna época de mi vida he sido ávido coleccionista de cosas de la naturaleza (como piedras, hojas, etc.)', 1,5),
    Question('Tengo habilidades para usar las palabras en sentido figurado (hacer metáforas)', 1,1),
    Question('Me gustaría trabajar con la contabilidad de una gran empresa', 2,2),
    Question('Puedo repetir bien las notas musicales cuando alguien me lo pide',3,6),
    Question('Puedo combinar bien los colores, formas, sombras y textura en un trabajo que realizo', 4,3),
    Question('Me agrada participar y disfruto mucho en actividades deportivas, tanto individuales como por equipo', 5,4),
    Question('Tengo facilidad para reconocer los méritos y éxitos de las demás personas', 1,7),
    Question('Pienso en la condición humana con frecuencia y en el lugar que yo tengo en este mundo', 1,8),
    Question('Busco y disfruto actividades recreativas como ir de pesca, acampar, etc.', 1,5),
    Question('Me gusta aprender frases y pensamientos célebres, recordarlos y usarlos en mi vida diaria', 1,1),
  Question('Los números siempre han sido algo importante en mi vida', 2,2),
  Question('Me siento orgulloso(a) de mis talentos por la música y los demás han reconocido también en mi, esas cualidades',3,6),
  Question('Me resulta sencillo construir y ver las cosas en tres dimensiones', 4,3),
  Question('Soy una persona activa y disfruto mucho del movimiento', 5,4),
  Question('Rápidamente me doy cuenta cuando alguien quiere manipular a los demás', 1,7),
  Question('Me siento feliz como miembro de mi familia y del lugar que ocupo en ella', 1,8),
  Question('Me gusta mucho tener mascotas y procuro que estén sanos y bien cuidados', 1,5),
  Question('Disfruto escribiendo y creo tener habilidad para usar correctamente las palabras, sintaxis y la semántica del lenguaje', 1,1),
  Question('Siempre trato de buscar la relación causa-efecto de la cosas o acontecimientos ', 2,2),
  Question('Tengo una gran colección de CD de música variada y disfruto escuchándola',3,6),
  Question('Tengo habilidad para crear y hacer cosas con las manos', 4,3),
  Question('Disfruto mucho de las actividades de la temporada de verano como nadar, correr olas, jugar paleta, etc.', 5,4),
  Question('Tengo bien desarrollada mi intuición y pronto me doy cuenta de las cosas usando mi 6º sentido', 1,7),
  Question('Me agrada como soy y tengo una clara idea de mis fortalezas y debilidades', 1,8),
  Question('Si pudiera sería miembro de las organizaciones que buscan proteger la flora y la fauna (ecología), preservando el cuidado de la naturaleza', 1,5),
    Question('Me agrada conversar bastante con los demás y contarle historias, acontecimientos y hechos reales o inventados', 1,1),
    Question('En mis pensamientos con frecuencia están las ideas lógicas, las hipótesis y las deducciones', 2,2),
    Question('A menudo me gusta cantar, bailar, zapatear y estar conectado con la música',3,6),
    Question('Necesito de imágenes, figuras, esquemas para entender mejor los hechos', 4,3),
    Question('Me agrada mucho las competencias deportivas y ver programas de TV de Olimpiadas (atletismo, gimnasia, voley, fútbol, etc.)', 5,4),
    Question('Soy de los que piensa, que todos somos iguales no desmerezco a nadie', 1,7),
    Question('Considero que soy una persona completamente honesta conmigo mismo', 1,8),
    Question('Amo la naturaleza, sus ríos, montañas, valles y lagos', 1,5)
  ];

}


 